default_platform(:ios)

TEMP_KEYCHAIN_USER = "alkincakiralar@makswin.com"
TEMP_KEYCHAIN_PASSWORD = "456789123Alkin"

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  desc "Description of what the lane does"
  lane :beta  do |options|
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD

    ensure_temp_keychain(keychain_name, keychain_password)

    increment_build_number(xcodeproj: "spmcachetet.xcodeproj")

    gym(
      scheme: "spmcachetet", 
      export_options: {
        method: "development"
      },
      silent: true,
      xcargs: "-allowProvisioningUpdates",
      output_name: "spmTEST.ipa",
      skip_codesigning: true
    )

    delete_temp_keychain(keychain_name)
  end
end

# xcodebuild -project "spmcachetet.xcodeproj" -scheme "spmcachetet" -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO

# xcodebuild -scheme spmcachetet build -allowProvisioningUpdates



