default_platform(:ios)

TEMP_KEYCHAIN_USER = "alkincakiralar@makswin.com"
TEMP_KEYCHAIN_PASSWORD = "456789123Alkin"

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: 0
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end

platform :ios do
  desc "Description of what the lane does"
  lane :beta  do |options|
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD

    ensure_temp_keychain(keychain_name, keychain_password)

    # increment_build_number(xcodeproj: "spmcachetet.xcodeproj")

    # disable_automatic_code_signing(path: "spmcachetet.xcodeproj")

    # build_app(
    #   scheme: "spmcachetet", 
    #   export_method: "development",
    #   output_name: "test.ipa",
    #   clean: options[:clean],
    #   skip_package_dependencies_resolution: options[:skip_package_dependencies_resolution]
    #   # silent: true,
    #   # clean: true
    # )

    gym(
      scheme: "spmcachetet", 
      export_method: "development"
    )

    # upload_to_testflight(ipa: "tasdaest.ipa")

    delete_temp_keychain(keychain_name)
  end
end