name: build-ios-app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploying to TestFlight
    runs-on: macos-latest

    steps:
      - name: "Cache: SPM"
        uses: actions/cache@v3
        with:
            path: /Users/runner/work/SPMCacheTest/SPMCacheTest/SourcePackages
            key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
            restore-keys: |
              ${{ runner.os }}-spm-

      - name: Xcode Build
        uses: actions/checkout@v1
      - run: cd /Users/runner/work/SPMCacheTest/SPMCacheTest; ls;
      - run: cd /Users/runner/work/SPMCacheTest/SPMCacheTest/SourcePackages; ls;
      # - run: cd /Users/runner/work/SPMCacheTest/SPMCacheTest; ls; echo go
      # - run: xcodebuild -project "spmcachetet.xcodeproj" -scheme "spmcachetet" -clonedSourcePackagesDirPath /Users/runner/work/SPMCacheTest/SPMCacheTest/SourcePackages -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO
      # - run: fastlane beta


      # /Users/runner/Library/Developer/Xcode/DerivedData/spmcachetet-bwrourzvvavfwebiubkpzheduuwk