name: build-ios-app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploying to TestFlight
    runs-on: macos-latest

    steps:
       - name: Swift Packages Cache
         uses: actions/cache@v2
         id: cache
         with:
          path: |
            /Users/runner/work/SPMCacheTest/SPMCacheTest/SourcePackages/
          key: ${{ runner.os }}-deps-v1-${{ hashFiles('spmcachetet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-deps-v1-

       - uses: actions/checkout@v1
       - run: xcodebuild -project "spmcachetet.xcodeproj" -scheme "spmcachetet" -clonedSourcePackagesDirPath /Users/runner/work/SPMCacheTest/SPMCacheTest/SourcePackages -destination "generic/platform=iOS" -configuration Release build CODE_SIGNING_ALLOWED=NO

#       version: 2.1

# jobs:
#   build:
#     macos:
#       xcode: "11.6.0"
#     steps:
#       - checkout
#       - restore_cache: 
#           key: spm-cache-{{ checksum "spm-cache-test.xcodeproj/project.xcworkspace/ xcshareddata/swiftpm/Package.resolved" }}
#   - run:
#           name: Install missing gems
#           command: bundle install
#       - run:
#           name: Build and test
#           command: bundle exec fastlane build_and_test
#       - save_cache:
#           paths:
#             - SourcePackages/
#           key: spm-cache-{{ checksum "spm-cache-test.xcodeproj/ project.xcworkspace/xcshareddata/ swiftpm/Package.resolved" }}