name: build-ios-app
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploying to TestFlight
    runs-on: macos-latest

    steps:
       - uses: actions/checkout@v1
      #  - run:  xcodebuild archive -scheme spmcachetet -sdk iphoneos -allowProvisioningUpdates -archivePath spmcachetet.xcarchive
       - run: xcodebuild -scheme spmcachetet build

       - name: Swift Packages Cache
         uses: actions/cache@v2
         id: cache
         with:
          path: |
            Build/SourcePackages
            Build/Build/Products
          key: ${{ runner.os }}-deps-v1-${{ hashFiles('spmcachetet.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved') }}
          restore-keys: ${{ runner.os }}-deps-v1-